apiVersion: v1
kind: Service
metadata:
  name: node-service-datacenter
  namespace: node-namespace-datacenter
spec:
  type: NodePort
  selector:
    app: node-app-datacenter
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
