apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment-datacenter
  namespace: node-namespace-datacenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-datacenter
  template:
    metadata:
      labels:
        app: node-app-datacenter
    spec:
      containers:
        - name: node-container-datacenter
          image: gcr.io/kodekloud/centos-ssh-enabled:node
          ports:
            - containerPort: 80
