apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  labels:
    app: k8s
    type: front-end
spec:
  replicas: 10
  selector:
    matchLabels:
      app: k8s
      type: front-end
  template:
    metadata:
      labels:
        app: k8s
        type: front-end
    spec:
      containers:
        - name: hello-kubernetess-container
          image: paulbouwer/hello-kubernetes:1.10
          ports:
          - containerPort: 8080
